use_frameworks!
platform :ios, '8.0'
target 'THMobileLibrary_Example' do
  pod 'THMobileLibrary', :path => '../'

  target 'THMobileLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'SDWebImage'
  pod 'AFNetworking', '~>3.1.0'
  end
end
